services:
 database:
   image: mysql
   container_name: mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: 1234
#     MYSQL_DATABASE: <database_name>
     MYSQL_USER: remo
     MYSQL_PASSWORD: 1234
   ports:
     - 3306:3306
     # Volume where to store the db
   volumes:
     - mysql_data:/var/lib/mysql

volumes:
 mysql_data:
